# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://avpsoftware.co.uk
title: AVP Software
email: info@avpsoftware.co.uk
author: AVP Software
description: > # "Write an awesome description for your new site here.
  We are a software consultancy, which also provides graphic design services.
  Specialists in XP, UX/UI, Java, Cloud Native and TDD.
copyright: 'Copyright &copy; 2019 AVP Software Limited. All Rights Reserved.'
credits: 'AVP Software Limited'

favicon_img_path: "img/favicon.ico"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: mail
    icon: envelope
    url: mailto:info@avpsoftware.co.uk
  - title: linkedin
    icon: linkedin
    url: https://www.linkedin.com/company/avp-software-limited
